# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_item_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='current_match',
            field=models.IntegerField(default=1),
        ),
    ]
